language: objective-c
env:
    global:
        - APP_NAME="ContinuousDistributionExample"
        - XCODE_SCHEME="$APP_NAME"
        - UNIT_TEST_SCHEME="${XCODE_SCHEME}Tests"
        - PROJECT_DIRECTORY="$PWD/"
before_install:
    - sudo gem install cocoapods
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
before_script:
    
script:
    - xctool -workspace $PROJECT_DIRECTORY$APP_NAME.xcworkspace -scheme $XCODE_SCHEME -sdk iphonesimulator
    - xctool test -workspace $PROJECT_DIRECTORY$APP_NAME.xcworkspace -scheme $UNIT_TEST_SCHEME -sdk iphonesimulator
after_success:
    
after_script:
    
    